allowBuilds:
  "@firebase/util": true
  protobufjs: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - "@aws-sdk/checksums@3.1000.28"
  - "@aws-sdk/client-s3@3.1111.0"
  - "@aws-sdk/core@3.977.8"
  - "@aws-sdk/credential-provider-env@3.972.69"
  - "@aws-sdk/credential-provider-http@3.972.71"
  - "@aws-sdk/credential-provider-ini@3.973.14"
  - "@aws-sdk/credential-provider-login@3.972.76"
  - "@aws-sdk/credential-provider-node@3.972.80"
  - "@aws-sdk/credential-provider-process@3.972.69"
  - "@aws-sdk/credential-provider-sso@3.973.13"
  - "@aws-sdk/credential-provider-web-identity@3.972.75"
  - "@aws-sdk/middleware-sdk-s3@3.972.74"
  - "@aws-sdk/nested-clients@3.997.43"
  - "@aws-sdk/s3-request-presigner@3.1111.0"
  - "@aws-sdk/signature-v4-multi-region@3.996.45"
  - "@aws-sdk/token-providers@3.1111.0"
  - "@aws-sdk/types@3.974.4"
  - "@aws-sdk/xml-builder@3.972.39"
